/**
 * 常量统一导出文件
 */

// API 相关常量
export { ADMIN_API_ENDPOINTS, HTTP_METHODS, HTTP_STATUS, WEB_API_ENDPOINTS } from './api';

// 路由相关常量
export { ADMIN_ROUTES, NOT_FOUND_ROUTE, QUERY_PARAMS, ROUTE_PARAMS, WEB_ROUTES } from './routes';

// 配置相关常量
export {
  ANIMATION_DURATION,
  BREAKPOINTS,
  CHARSET,
  CONTENT_TYPES,
  DEFAULT_VALUES,
  FILE_TYPES,
  IMAGE_TYPES,
  LOG_LEVELS,
  PAGINATION,
  STORAGE_KEYS,
  TIMEOUTS,
  VALIDATION,
} from './config';

// 消息相关常量
export {
  BUTTON_TEXTS,
  CONFIRM_MESSAGES,
  ERROR_MESSAGES,
  INFO_MESSAGES,
  STATUS_LABELS,
  SUCCESS_MESSAGES,
  VALIDATION_MESSAGES,
  WARNING_MESSAGES,
} from './messages';

// 样式相关常量
export {
  BORDER_RADIUS,
  COLORS,
  CSS_CLASSES,
  FONT_SIZES,
  ICON_SIZES,
  SHADOWS,
  SPACING,
  TRANSITIONS,
  Z_INDEX,
} from './styles';
